name = "dreamshift-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"

[ai]
binding = "AI"

[[vectorize]]
binding   = "VEC"
index_name = "dreamshift-kb" 

[[d1_databases]]
binding = "dreamshift_ai_db"
database_name = "dreamshift-ai-db"
database_id = "a95f35ee-b9a0-4c55-9c27-0d1429a4b60e"
migrations_dir = "migrations"